name: PyPi deployment

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish swap
    runs-on: ubuntu-latest
    steps:
      - name: Installing deps
        run: |
          pip3 install --upgrade setuptools 
          pip3 install --upgrade wheel
          pip3 install --upgrade twine
      - name: Checkout
        uses: actions/checkout@v2
      - name: Building swap
        run: python3 setup.py sdist bdist_wheel
      - name: Publishing
        run: "python3 -m twine upload --repository-url https://upload.pypi.org/legacy/ dist/* -u 'mathix420' -p '${{ secrets.PYPI_PASSWORD }}'"
